FROM python:3


ENV APP /app

RUN mkdir $APP
WORKDIR $APP

ADD *.py /
ENV MARAPHONE_BOT_TOKEN="1297621234:AAHxnGhQhb4vvpbMDl9cSoO82Le0Qu54zKs"

RUN pip install pyTelegramBotAPI pytz schedule

CMD [ "python3", "./bot.py" ]